### PR TITLE
Use biome for code formatting

### PR DESCRIPTION
**Pull request by kaja-osojnik**
Implementing the Biome tool for formatting and linting and fixing issues or errors flagged during the formatting process.

### CODE REVIEW

**Comment by matevz** [comment]
In other projects we simply use https://www.npmjs.com/package/prettier. Any reason why not to use it here too? Also what's with the 8 chars per tab? Usually it's 4 or 2.

**Comment by kaja-osojnik** [comment]
> In other projects we simply use https://www.npmjs.com/package/prettier. Any reason why not to use it here too? Also what's with the 8 chars per tab? Usually it's 4 or 2.

@lukaw3d recommended Biome. For spacing - it seems like that was a default setting, changed it to 2-spaced indentation.

**Comment by lukaw3d** [comment]
I prefer eslint+prettier. But that will require a week of senior frontend engineer time when migrating to next version of either.

Biome is fine. Or, if Nick is listening, https://github.com/xojs/xo. But configuring vscode for each is risky and annoying, so I just run them in console.

**Review by matevz — APPROVED** [review]

**Comment by lukaw3d** [comment]
Combined some commits and split out the manually fixed biome errors to make them more obvious

**Comment by lukaw3d** [comment]
Rebased

**Pull request merged**
